apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-dp
  labels:
    app: health-dp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: docker-health
  template:
    metadata:
      labels:
        app: docker-health
    spec:
      containers:
        - name: docker-health
          image: vanyamn/health
          ports:
          - containerPort: 8000
          env:
          - name: HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: health-cm
                key: port
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: health-cm
                key: databaseurl
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: health-secret
                key: username    
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: health-secret
                key: password   
      imagePullSecrets:
        - name: regcred